# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: RubyMetric.chsrc
PackageVersion: 0.1.9
PackageLocale: en-US
Publisher: RubyMetric
PackageName: chsrc
License: GPL-3.0-or-later,MIT
ShortDescription: Change Source for every software on every platform
ManifestType: defaultLocale
ManifestVersion: 1.9.0
